# Generated by Django 4.0.3 on 2024-05-21 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion_2023_LCK_summer',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('pick', models.IntegerField(db_column='pick', default=0)),
                ('ban', models.IntegerField(db_column='ban', default=0)),
                ('win', models.IntegerField(db_column='win', default=0)),
                ('lose', models.IntegerField(db_column='lose', default=0)),
                ('patch', models.TextField(db_column='patch', default='-')),
            ],
            options={
                'db_table': 'champion_2023_LCK_summer',
            },
        ),
        migrations.CreateModel(
            name='Champion_2024_LCK_spring',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('pick', models.IntegerField(db_column='pick', default=0)),
                ('ban', models.IntegerField(db_column='ban', default=0)),
                ('win', models.IntegerField(db_column='win', default=0)),
                ('lose', models.IntegerField(db_column='lose', default=0)),
                ('patch', models.TextField(db_column='patch', default='-')),
            ],
            options={
                'db_table': 'champion_2024_LCK_spring',
            },
        ),
        migrations.CreateModel(
            name='Ranking_2023_LCK_spring',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_2023_LCK_spring',
            },
        ),
        migrations.CreateModel(
            name='Ranking_2023_LCK_summer',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_2023_LCK_summer',
            },
        ),
        migrations.CreateModel(
            name='Ranking_2024_LCK_spring',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_2024_LCK_spring',
            },
        ),
        migrations.CreateModel(
            name='Ranking_2024_LCK_spring_player',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('date', models.TextField(db_column='date', default='-')),
                ('name', models.TextField(db_column='name', default='-')),
                ('nickname', models.TextField(db_column='nickname', default='-')),
                ('team', models.TextField(db_column='team', default='-')),
                ('position', models.TextField(db_column='position', default='-')),
            ],
            options={
                'db_table': 'ranking_2024_LCK_spring_player',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('team1_name', models.TextField(db_column='team1_name', default='-')),
                ('team2_name', models.TextField(db_column='team2_name', default='-')),
                ('team1_score', models.IntegerField(db_column='team1_score', default=0)),
                ('team2_score', models.IntegerField(db_column='team2_score', default=0)),
                ('datetime', models.DateTimeField(db_column='datetime', default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('league_version', models.TextField(db_column='league_version', default='-')),
                ('live_version', models.TextField(db_column='live_version', default='-')),
            ],
            options={
                'db_table': 'version',
            },
        ),
    ]
