# Generated by Django 4.0.3 on 2023-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='key',
            field=models.IntegerField(db_column='key', primary_key=True, serialize=False),
        ),
    ]
