# Generated by Django 5.0.1 on 2024-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_LCK_2024_Summer',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('tricode', models.TextField(db_column='tricode', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_LCK_2024_summer',
            },
        ),
    ]
