# Generated by Django 4.0.3 on 2024-05-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking_2024_lck_spring_player',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ranking_2024_lck_spring_player',
            name='name',
        ),
        migrations.AddField(
            model_name='ranking_2024_lck_spring_player',
            name='POG_point',
            field=models.IntegerField(db_column='POG_point', default=0),
        ),
    ]
