# Generated by Django 4.0.3 on 2023-11-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champion_23_summer',
            new_name='Champion_23_LCK_summer',
        ),
        migrations.AlterModelTable(
            name='champion_23_lck_summer',
            table='champion_23_LCK_summer',
        ),
    ]
