# Generated by Django 4.0.3 on 2023-04-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_schedule23spring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='date')),
                ('team1', models.TextField(db_column='team1')),
                ('team2', models.TextField(db_column='team2')),
                ('team1_score', models.IntegerField(db_column='team1_score')),
                ('team2_score', models.IntegerField(db_column='team2_score')),
                ('type', models.IntegerField(db_column='type')),
            ],
            options={
                'db_table': 'schedule_23spring',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Schedule23Spring',
        ),
    ]
