# Generated by Django 4.0.3 on 2024-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_schedule_team2_tricode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='team2_tricode',
            field=models.TextField(db_column='team2_tricode', default='-'),
        ),
    ]
