# Generated by Django 4.0.3 on 2024-05-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_ranking_2024_lck_spring_player_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking_2024_lck_spring_player',
            name='name',
            field=models.TextField(db_column='name', default='-'),
        ),
    ]
