# Generated by Django 5.0.1 on 2024-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_ranking_lck_2024_summer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion_LCK_2024_Summer',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('pick', models.IntegerField(db_column='pick', default=0)),
                ('ban', models.IntegerField(db_column='ban', default=0)),
                ('win', models.IntegerField(db_column='win', default=0)),
                ('lose', models.IntegerField(db_column='lose', default=0)),
                ('patch', models.TextField(db_column='patch', default='-')),
            ],
            options={
                'db_table': 'champion_LCK_2024_Summer',
            },
        ),
    ]
