# Generated by Django 4.0.3 on 2023-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_schedule_id_alter_schedule_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name')),
                ('tricode', models.TextField(db_column='tricode')),
                ('game_win', models.IntegerField(db_column='game_win')),
                ('game_lose', models.IntegerField(db_column='game_lose')),
                ('set_win', models.IntegerField(db_column='set_win')),
                ('set_lose', models.IntegerField(db_column='set_lose')),
                ('etc', models.TextField(db_column='etc')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
    ]
