# Generated by Django 4.0.3 on 2023-04-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_schedule_delete_schedule23spring'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
