# Generated by Django 5.0.1 on 2024-06-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_champion_lck_2024_summer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_LCK_2024_Summer_player',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('nickname', models.TextField(db_column='nickname', default='-')),
                ('name', models.TextField(db_column='name', default='-')),
                ('team', models.TextField(db_column='team', default='-')),
                ('tricode', models.TextField(db_column='tricode', default='-')),
                ('position', models.TextField(db_column='position', default='-')),
                ('POG_point', models.IntegerField(db_column='POG_point', default=0)),
            ],
            options={
                'db_table': 'ranking_LCK_2024_summer_player',
            },
        ),
    ]
