# Generated by Django 4.0.3 on 2024-01-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_champion_24_lck_spring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_24_spring_regular',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('tricode', models.TextField(db_column='tricode', default='-')),
                ('game_win', models.IntegerField(db_column='game_win', default=0)),
                ('game_lose', models.IntegerField(db_column='game_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_24_spring_regular',
            },
        ),
    ]
