# Generated by Django 4.0.3 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_ranking_2024_lck_spring_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_2024_MSI',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_2024_MSI',
            },
        ),
    ]
