# Generated by Django 4.0.3 on 2024-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_ranking_2024_msi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion_2024_MSI',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('pick', models.IntegerField(db_column='pick', default=0)),
                ('ban', models.IntegerField(db_column='ban', default=0)),
                ('win', models.IntegerField(db_column='win', default=0)),
                ('lose', models.IntegerField(db_column='lose', default=0)),
                ('patch', models.TextField(db_column='patch', default='-')),
            ],
            options={
                'db_table': 'champion_2024_MSI',
            },
        ),
        migrations.DeleteModel(
            name='Ranking_2024_MSI',
        ),
    ]
