# Generated by Django 4.0.3 on 2024-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_ranking_24_spring_regular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_24_spring_player',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('date', models.TextField(db_column='date', default='-')),
                ('name', models.TextField(db_column='name', default='-')),
                ('nickname', models.TextField(db_column='nickname', default='-')),
                ('team', models.TextField(db_column='team', default='-')),
                ('position', models.TextField(db_column='position', default='-')),
            ],
            options={
                'db_table': 'ranking_24_spring_player',
            },
        ),
    ]
