# Generated by Django 4.0.3 on 2023-04-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_23_msi_playin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField(db_column='team1')),
                ('team2', models.TextField(db_column='team2')),
                ('team1_score', models.IntegerField(db_column='team1_score')),
                ('team2_score', models.IntegerField(db_column='team2_score')),
            ],
            options={
                'db_table': 'Ranking_23_msi_playin',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
