# Generated by Django 4.0.3 on 2023-05-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_schedule_etc_alter_ranking_etc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='Ranking_23_spring_regular',
        ),
        migrations.AlterModelTable(
            name='ranking_23_spring_regular',
            table='ranking_23_spring_regular',
        ),
    ]
