# Generated by Django 4.0.3 on 2024-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_schedule_datetime_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='team1_tricode',
            field=models.TextField(db_column='team1_tricode', default='-'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team2_tricode',
            field=models.TextField(db_column='team2_tricode', default='-'),
        ),
    ]
