# Generated by Django 4.0.3 on 2023-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_ranking_ranking_23_spring_regular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='team1_tricode',
            field=models.TextField(db_column='team1_tricdoe', default=' - '),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team2_tricode',
            field=models.TextField(db_column='team2_tricode', default=' - '),
        ),
        migrations.AlterField(
            model_name='ranking_23_spring_regular',
            name='name',
            field=models.TextField(db_column='name', default=' - '),
        ),
        migrations.AlterField(
            model_name='ranking_23_spring_regular',
            name='tricode',
            field=models.TextField(db_column='tricode', default=' - '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ampm',
            field=models.TextField(db_column='ampm', default=' - '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(db_column='day', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.IntegerField(db_column='hour', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='min',
            field=models.IntegerField(db_column='min', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(db_column='month', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team1_name',
            field=models.TextField(db_column='team1_name', default=' - '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team1_score',
            field=models.IntegerField(db_column='team1_score', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team2_name',
            field=models.TextField(db_column='team2_name', default=' - '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='team2_score',
            field=models.IntegerField(db_column='team2_score', default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.TextField(db_column='weekday', default=' - '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(db_column='year', default=0),
        ),
    ]
