# Generated by Django 4.0.3 on 2024-05-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_schedule_team1_tricode_schedule_team2_tricode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team1_tricode',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='team2_tricode',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tournament',
            field=models.TextField(db_column='tournament', default='-'),
        ),
    ]
