# Generated by Django 4.0.3 on 2024-05-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_schedule_etc_remove_schedule_team1_tricode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='etc',
            field=models.TextField(db_column='etc', default='-'),
        ),
    ]
