# Generated by Django 4.0.3 on 2023-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_schedule_ampm_alter_schedule_team1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking_23_spring_regular',
            name='name',
            field=models.TextField(db_column='name', default='-'),
        ),
        migrations.AlterField(
            model_name='ranking_23_spring_regular',
            name='tricode',
            field=models.TextField(db_column='tricode', default='-'),
        ),
    ]
