# Generated by Django 4.0.3 on 2023-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_ranking_23_spring_regular_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_23_summer_regular',
            fields=[
                ('key', models.IntegerField(db_column='key', default=0, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('tricode', models.TextField(db_column='tricode', default='-')),
                ('game_win', models.IntegerField(db_column='game_win', default=0)),
                ('game_lose', models.IntegerField(db_column='game_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_23_summer_regular',
            },
        ),
    ]
