# Generated by Django 4.0.3 on 2024-05-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_schedule_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='team1_tricode',
            field=models.TextField(db_column='team1_tricode', default='-'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='team2_tricode',
            field=models.TextField(db_column='team2_tricode', default='-'),
        ),
    ]
