# Generated by Django 4.0.3 on 2024-05-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_schedule_team1_tricode_schedule_team2_tricode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking_2023_lck_spring',
            name='tricode',
            field=models.TextField(db_column='tricode', default='-'),
        ),
        migrations.AddField(
            model_name='ranking_2023_lck_summer',
            name='tricode',
            field=models.TextField(db_column='tricode', default='-'),
        ),
    ]
