# Generated by Django 4.0.3 on 2023-07-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_ranking_23_summer_regular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('key', models.IntegerField(db_column='key', default=0, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('pick', models.IntegerField(db_column='pick', default=0)),
                ('ban', models.IntegerField(db_column='ban', default=0)),
                ('win', models.IntegerField(db_column='win', default=0)),
                ('lose', models.IntegerField(db_column='lose', default=0)),
                ('patch', models.TextField(db_column='patch', default='-')),
            ],
            options={
                'db_table': 'chamipon',
            },
        ),
    ]
