# Generated by Django 4.0.3 on 2023-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='key',
            field=models.AutoField(db_column='key', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ranking_23_spring_regular',
            name='key',
            field=models.AutoField(db_column='key', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ranking_23_summer_regular',
            name='key',
            field=models.AutoField(db_column='key', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='key',
            field=models.AutoField(db_column='key', default=0, primary_key=True, serialize=False),
        ),
    ]
