# Generated by Django 4.0.3 on 2024-05-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_ranking_2023_lck_spring_tricode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_LCK_2024_spring',
            fields=[
                ('key', models.AutoField(db_column='key', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name', default='-')),
                ('tricode', models.TextField(db_column='tricode', default='-')),
                ('match_win', models.IntegerField(db_column='match_win', default=0)),
                ('match_lose', models.IntegerField(db_column='match_lose', default=0)),
                ('set_win', models.IntegerField(db_column='set_win', default=0)),
                ('set_lose', models.IntegerField(db_column='set_lose', default=0)),
                ('etc', models.TextField(db_column='etc', default='-')),
            ],
            options={
                'db_table': 'ranking_LCK_2024_spring',
            },
        ),
        migrations.RenameModel(
            old_name='Champion_2023_LCK_summer',
            new_name='Champion_LCK_2023_summer',
        ),
        migrations.RenameModel(
            old_name='Champion_2024_LCK_spring',
            new_name='Champion_LCK_2024_spring',
        ),
        migrations.RenameModel(
            old_name='Champion_2024_MSI',
            new_name='Champion_MSI_2024',
        ),
        migrations.RenameModel(
            old_name='Ranking_2023_LCK_spring',
            new_name='Ranking_LCK_2023_spring',
        ),
        migrations.RenameModel(
            old_name='Ranking_2023_LCK_summer',
            new_name='Ranking_LCK_2023_summer',
        ),
        migrations.RenameModel(
            old_name='Ranking_2024_LCK_spring_player',
            new_name='Ranking_LCK_2024_spring_player',
        ),
        migrations.DeleteModel(
            name='Ranking_2024_LCK_spring',
        ),
        migrations.AlterModelTable(
            name='champion_lck_2023_summer',
            table='champion_LCK_2023_summer',
        ),
        migrations.AlterModelTable(
            name='champion_lck_2024_spring',
            table='champion_LCK_2024_spring',
        ),
        migrations.AlterModelTable(
            name='champion_msi_2024',
            table='champion_MSI_2024',
        ),
        migrations.AlterModelTable(
            name='ranking_lck_2023_spring',
            table='ranking_LCK_2023_spring',
        ),
        migrations.AlterModelTable(
            name='ranking_lck_2023_summer',
            table='ranking_LCK_2023_summer',
        ),
        migrations.AlterModelTable(
            name='ranking_lck_2024_spring_player',
            table='ranking_LCK_2024_spring_player',
        ),
    ]
