# Generated by Django 4.0.3 on 2024-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_ranking_lck_2024_spring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking_lck_2024_spring_player',
            name='tricode',
            field=models.TextField(db_column='tricode', default='-'),
        ),
    ]
