# Generated by Django 4.0.3 on 2023-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_champion_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.TextField(db_column='year', default='-'),
        ),
    ]
